MasterChef.Api/Models/ErrorViewModel.cs
namespace MasterChef.Api.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MasterChef.Api/Controllers/CadastrarReceitaController.cs
using Masterchef.Service;
using MasterChef.Api.Models;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;

namespace MasterChef.Api.Controllers
{
    public class CadastrarReceitaController : Controller
    {
        private readonly IRecipeService _recipeService;

        public CadastrarReceitaController(IRecipeService recipeService)
        {
            _recipeService = recipeService;
        }
        // GET: CadastrarReceitaController
        public ActionResult Index()
        {
            var recipt = new Recipe();
            return View(recipt);
        }

        // GET: CadastrarReceitaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CadastrarReceitaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CadastrarReceitaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Recipe receipe)
        {
            try
            {
                var invalid = _ValidateRecipe(receipe);

                if(invalid)
                {
                    return View(nameof(Index), receipe);
                }

                await _recipeService.AddRecipe(receipe);

                return RedirectToAction("Index", "Home");
            }
            catch(Exception e)
            {
                ModelState.AddModelError("Title", "Já existe uma receita com esse título.");
                return View(nameof(Index), receipe);
            }
        }

        // GET: CadastrarReceitaController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var recipe = await _recipeService.GetRecipe(id);

            return View(nameof(Index), recipe);
        }

        // POST: CadastrarReceitaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Recipe receipe)
        {
            try
            {
                await _recipeService.UpdateRecipe(id, receipe); 
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: CadastrarReceitaController/Delete/5
        public ActionResult Delete(int id)
        {
            _recipeService.Delete(id);
            return RedirectToAction("Index", "Home");
        }

        // POST: CadastrarReceitaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        private bool _ValidateRecipe(Recipe receipe)
        {
            if (receipe.Tags.Any(q => string.IsNullOrEmpty(q.Name)))
            {
                ModelState.AddModelError("Tags", "Tag não pode ser vazia");
                return true;
            }

            if (receipe.Ingredients.Count == 0)
            {
                ModelState.AddModelError("Ingredients", "Ingrediente não pode ser vazia");
                return true;
            }

            if (receipe.PrepareModes.Count == 0)
            {
                ModelState.AddModelError("PrepareModes", "Modo de preparo não pode ser vazia");
                return true;
            }

            return false;
        }
    }
    

}

MasterChef.Api/Controllers/HomeController.cs
using Masterchef.Domain;
using Masterchef.Service;
using MasterChef.Api.Models;
using Microsoft.AspNetCore.Mvc;

namespace MasterChef.Api.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRecipeService _recipeService;

        public HomeController( IRecipeService recipeService)
        {
            _recipeService = recipeService;
        }

        public async Task<IActionResult> Index()
        {
            var recipes = await _recipeService.GetAll();
            
            return View(nameof(Index), recipes);

        }
        
        [HttpGet("/receitas")]
        public async Task<IActionResult> Get()
        {

            var receitas = await _recipeService.GetAll();
            
            return Json(receitas);
        }
        
        [HttpPost("Post")]
        public async Task<IActionResult> Post(Recipe recipe)
        {
            try
            {
                await _recipeService.AddRecipe(recipe);

                return Ok(recipe);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            
        }
    }
}

MasterChef.Api/Views/CadastrarReceita/Index.cshtml
@model Recipe

@{
    ViewBag.Title = "Cadastro de Receita";

    var action = "edit";
    if(Model.Id == 0)
    {
        action = "create";
    }
}

<h2>Cadastro de Receita</h2>

<form asp-controller="cadastrarReceita" asp-action="@action" method="post">
    <div class="form-group">
        <label for="title">Título</label>
        <input type="text" class="form-control" id="title" name="Title" value="@Model.Title" required>
    </div>
    <div class="form-group">
        <label for="foto">Foto</label>
        <input placeholder="Inserir Link da imagem" type="text" class="form-control" id="foto" name="Foto" value="@Model.Foto" required>
    </div>
    <div class="form-group">
        <label for="description">Descrição</label>
        <textarea class="form-control" id="description" name="Description" rows="3" required>@Model.Description</textarea>
    </div>
    <div class="form-group">
        <label for="category">Categoria</label>
        <select class="form-control" id="category" name="Category.Title" required>
            <option value="">Selecione uma categoria</option>
            <option selected value="Doces">Doces</option>
            <option value="Carnes">Carnes</option>
            <option value="Aves">Aves</option>
            <option value="Frutos do Mar">Frutos do Mar</option>
            <option value="Saladas">Saladas</option>
        </select>
    </div>
    <div class="form-group">
        <label>Tags</label>
        <ul id="tags">
            @if(Model.Tags.Count > 0)
            {
                int counter = 0;
                @foreach (var step in Model.Tags)
                {
                    <li>
                        <input type="text" name="tags[@counter].Name" value="@step.Name">
                        <button type="button" class="btn btn-danger" onclick="$(this).closest('li').remove()">Remover</button>
                    </li>

                    counter++;
                }
            }

            @if (Model.Tags.Count == 0)
            {
                <li>
                    <input type="text" name="tags[0].Name">
                    <button type="button" class="btn btn-danger" onclick="$(this).closest('li').remove()">Remover</button>
                </li>
            }
            
        </ul>
        <button type="button" class="btn btn-primary" onclick="adicionarTags()">Adicionar Tags</button>
    </div>
    <div class="form-group">
        <label>Ingredientes</label>
        <ul id="ingredients">
            @if (Model.Ingredients.Count > 0)
            {
                int counter = 0;
                @foreach (var step in Model.Ingredients)
                {
                    <li>
                        <input type="text" name="ingredients[@counter].Name" value="@step.Name">
                        <button type="button" class="btn btn-danger" onclick="$(this).closest('li').remove()">Remover</button>
                    </li>

                    counter++;
                }
            }

            @if (Model.Ingredients.Count == 0)
            {
                <li>
                    <input type="text" name="ingredients[0].Name">
                    <button type="button" class="btn btn-danger" onclick="$(this).closest('li').remove()">Remover</button>
                </li>
            }
        </ul>
        <button type="button" class="btn btn-primary" onclick="adicionarIngrediente()">Adicionar Ingrediente</button>
    </div>
    <div class="form-group">
        <label >Modo de Preparo</label>
        <ul id="prepareModes">
            @if (Model.PrepareModes.Count > 0)
            {
                int counter = 0;
                @foreach (var step in Model.PrepareModes)
                {
                    <li>
                        <input type="text" name="prepareModes[@counter].Name" value="@step.Name">
                        <button type="button" class="btn btn-danger" onclick="$(this).closest('li').remove()">Remover</button>
                    </li>

                    counter++;
                }
            }

            @if (Model.PrepareModes.Count == 0)
            {
                <li>
                    <input type="text" name="prepareModes[0].Name">
                    <button type="button" class="btn btn-danger" onclick="$(this).closest('li').remove()">Remover</button>
                </li>
            }
        </ul>
        <button type="button" class="btn btn-primary" onclick="adicionarModoDePreparo()">Adicionar Modo de Preparo</button>
    </div>

    <span asp-validation-for="Title" class="text-danger"></span>
    <span asp-validation-for="Tags" class="text-danger"></span>
    <span asp-validation-for="Ingredients" class="text-danger"></span>
    <span asp-validation-for="PrepareModes" class="text-danger"></span>
    <br/>
    <button type="submit" class="btn btn-success" >Salvar</button>
    <a href="@Url.Action("Index", "Home")" class="btn btn-default">Cancelar</a>

</form>

<script>
    let ingredientsCount = @Model.Ingredients.Count;
    let prepareModesCount = @Model.PrepareModes.Count;
    let tagsCount = @Model.Tags.Count;

    function adicionarTags() {
        tagsCount++
        var ingredientes = $("#tags");
        var li = $("<li>");
        var input = $("<input>").attr("type", "text").attr("name", `tags[${tagsCount}].Name`);
        var button = $("<button>").attr("type", "button").addClass("btn").addClass("btn-danger").text("Remover").on("click", function () {
            $(this).closest("li").remove();
        });
        li.append(input).append(button);
        ingredientes.append(li);
    }

    function adicionarIngrediente() {
        ingredientsCount++
        var ingredientes = $("#ingredients");
        var li = $("<li>");
        var input = $("<input>").attr("type", "text").attr("name", `ingredients[${ingredientsCount}].Name`);
        var button = $("<button>").attr("type", "button").addClass("btn").addClass("btn-danger").text("Remover").on("click", function () {
            $(this).closest("li").remove();
        });
        li.append(input).append(button);
        ingredientes.append(li);
    }

    function adicionarModoDePreparo() {
        prepareModesCount++
        var modoDePreparo = $("#prepareModes");
        var li = $("<li>");
        var input = $("<input>").attr("type", "text").attr("name", `prepareModes[${prepareModesCount}].Name`);
        var button = $("<button>").attr("type", "button").addClass("btn").addClass("btn-danger").text("Remover").on("click", function () {
            $(this).closest("li").remove();
        });
        li.append(input).append(button);
        modoDePreparo.append(li);
    }

</script>

MasterChef.Api/Views/Home/Index.cshtml
@model IEnumerable<Recipe>

<!DOCTYPE html>
<html>
<head>
    <title>Listagem de Receitas</title>
    <style>
        /* Estilo CSS para a página */
        body {
            font-family: Arial, sans-serif;
        }

        h1 {
            text-align: center;
            margin-top: 50px;
            font-size: 40px;
        }

        .receipes {
            display: flex;
            justify-content: flex-start;
            align-items: center;
            width: 100%;

        }

        .recipe {
            margin: 50px auto;
            width: 80%;
            border: 1px solid #ccc;
            padding: 20px;
            border-radius: 10px;
            margin-right: 1%;
            display:flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

            .recipe h2 {
                font-size: 30px;
                margin-bottom: 20px;
            }

            .recipe img {
                display: block;
                margin: auto;
                width: 60%;
                margin-bottom: 20px;
            }

            .recipe p {
                margin-bottom: 20px;
                font-size: 18px;
                line-height: 24px;
            }

            .recipe ul {
                margin-bottom: 20px;
                font-size: 18px;
                line-height: 24px;
            }

            .recipe li {
                margin-left: 20px;
            }

            .recipe a {
                display: block;
                text-align: right;
                font-size: 18px;
                text-decoration: none;
                color: #000;
            }

                .recipe a:hover {
                    color: #666;
                }

            .recipe .category {
                margin-top: 20px;
                font-size: 20px;
                font-weight: bold;
            }

            .buttons {
                display: flex
            }
            .btn {
                margin-right: 1%
            }
    </style>
</head>
<body>
    <h1>Listagem de Receitas</h1>

    <div class="receipes">
        @foreach (var recipe in Model)
        {
                <div class="recipe">
                    <h2>@recipe.Title</h2>
                    <img src="@recipe.Foto" alt="@recipe.Title">
                <span><strong>Descrição: </strong>@recipe.Description</span>
                
                <br/>

                <h3>Tags:</h3>
                <ul>
                    @foreach (var tag in recipe.Tags)
                    {
                        <li>@tag.Name</li>
                    }
                </ul>

                <h3>Ingredientes:</h3>
                <ul>
                    @foreach (var ingredient in recipe.Ingredients)
                    {
                        <li>@ingredient.Name</li>
                    }
                </ul>

                <h3>Modo de Preparo:</h3>
                    <ol>
                        @foreach (var step in recipe.PrepareModes)
                        {
                            <li>@step.Name</li>
                        }
                    </ol>

                <div class="category">
                    Categoria: <span>@recipe.Category.Title</span>
                </div>

                <div class="buttons">
                    <a href="cadastrarReceita/edit/@recipe.Id" class="btn btn-warning">Editar</a>
                    <button class="btn btn-danger" onclick="deleteRecipe(@recipe.Id)">Deletar</button>
                </div>
            </div>

            
        }
    </div>
</body>

</html>

<script>
    function deleteRecipe(id) {
        console.log(id)

        $.ajax({
            url: `CadastrarReceita/delete/${id}`,
            type: "DELETE",
            json: { id },
            success: function (result) {
                console.log(result);
                window.location.href = window.location.href
            },
            error: function (error) {
                console.log(error);
            }
        });
    }


</script>

MasterChef.Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MasterChef.Api</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MasterChef.Api.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MasterChef.Api</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CadastrarReceita" asp-action="Index">CadastrarReceita</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MasterChef.Api - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>